workspace:
  base: /front
  path: src/github.com/Howard21432134/Drone_test
pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run build
  publish:
    image: nginx:latest
    repo: Howard21432134/Drone_test
    tags: ["latest","v2"]
    secrets: [docker_username,docker_password]
    dockerfile: Dockerfile